- app/users/urls.py
- app/users/views.py
#️⃣ Issue Number: #2
유저 관련 api 세팅
> Feat: users api 세팅 완료 (#2)

- app/alerts/urls.py
- app/alerts/views.py
- app/bookmarks/urls.py
- app/bookmarks/views.py
- app/comments/urls.py
- app/comments/views.py
- app/fridges/urls.py
- app/fridges/views.py
- app/ingredients/urls.py
- app/ingredients/views.py
- app/likes/urls.py
- app/likes/views.py
- app/main/urls.py
- app/main/views.py
- app/recipes/urls.py
- app/recipes/views.py
> Feat: API 틀 작성 및 주소 수정 (#2)

- app/recipes/views.py
> Feat: 특정 레시피 삭제 API 작성 (#20)

- app/recipes/views.py
> Feat: 특정 레시피 조회 (#22)

- app/fridges/urls.py
- app/fridges/views.py
> Feat fridges model api 개발 #24

- app/recipes/views.py
> Feat: 선택한 재료들의 id를 보내면 관련 레시피 출력 (#36)

- app/ingredients/views.py
- app/recipes/views.py
> Feat: 타입별 재료조회 및 레시피 뷰 수정 (#38)

- app/ingredients/views.py
- app/recipes/views.py
> Feat: 특정 레시피 조회 기능 수정 및 검색기능 추가 (#42)

- app/recipes/views.py
> Ref: 레시피, 댓글 수정 및 삭제 기능 푸쉬 (#45)

- app/recipes/views.py
> Ref: 카테고리별 레시피 조회기능 수정 (#49)

- app/alerts/serializers.py
- app/alerts/views.py
- app/main/serializers.py
- app/main/views.py
> Feat: modify alert, mainpage api (#52)

- app/main/serializers.py
- app/main/views.py
> Feat: main page api modify (#54)

- app/config/asgi.py
- app/config/settings.py
> Fix: 되돌리기

- app/users/serializers.py
- app/users/urls.py
- app/users/views.py
> Feat: User API (#61)

- app/alerts/views.py
- app/bookmarks/views.py
- app/comments/views.py
- app/config/settings.py
- app/fridges/views.py
- app/likes/views.py
- app/users/serializers.py
- app/users/views.py
> Feat: user API modify (#70)

- .github/workflows/deploy-dev-ncp.yml
develop 브랜치로 push 되면 자동으로 배포될 수 있도록 workflow 작성
> Deploy: 자동 배포 workflow

- .github/workflows/deploy-dev-ncp.yml
> Docs yjm ncp auto deploy

- .github/workflows/deploy-dev-ncp.yml
> Deploy: 자동 배포 테스트2

- app/alerts/views.py
- app/bookmarks/views.py
- app/comments/views.py
- app/fridges/views.py
- app/likes/views.py
- app/users/views.py
> Feat: User API 수정 #76

- proxy/ndd.conf
> Deploy: 프론트 서버 포함

- app/recipes/serializers.py
- app/recipes/utils.py
- app/recipes/views.py
> Feat jeongho recipe api #81

- app/ingredients/views.py
- app/recipes/views.py
> Feat: 토큰에서 유저 아이디 받아오기 (#84)

- app/alerts/urls.py
- app/users/serializers.py
- app/users/urls.py
- app/users/views.py
> Feat: mypage API (#80)

- app/users/urls.py
- app/users/views.py
> Feat: 알림 여부 조회 기능 추가 #93

- app/main/views.py
> Feat: main page API 수정 (#95)

- app/users/views.py
> Fix: 유저 알림 여부 1만 return 되는것 수정 #92

- app/recipes/views.py
> Fix: 레시피 스텝 순서대로 나오게 정렬

- app/users/views.py
> Feat: 사용자 이미지 빈 문자열로 저장 (#106)

- app/alerts/apps.py
- app/alerts/signals.py
- app/alerts/views.py
- app/likes/views.py
> Feat: alert signal 개발 (#110)

- app/recipes/views.py
- app/users/views.py
#️⃣ Issue Number: #113
마이페이지 접근시 대표이미지 출력 오류 수정
특정 레시피 접근시 레시피 작성자 이미지 및 댓글 작성자 이미지 출력 오류 수정
> Feat: 마이페이지 및 특정레시피 유저 이미지 받아오기 #113

- app/alerts/views.py
> Feat: 알람 상태 관리 API 작성 완료 (#115)

- app/comments/urls.py
- app/comments/views.py
- app/recipes/urls.py
- app/recipes/views.py
- app/users/views.py
#️⃣ Issue Number: #117
comments -> urls.py, view.py 수정
users -> views.py: MypageView 수정
recipes -> views.py 수정
> Fix: 댓글, 레시피, 유저 뷰 수정 (#117)

- app/config/urls.py
- app/fridges/urls.py
- app/fridges/views.py
> Fix: config url 수정

- app/comments/views.py
> Fix: 댓글 수정 API 수정 (#120)

- app/alerts/signals.py
> Feat: signal modify

- app/ingredients/views.py
> Fix: 재료 검색 조회 부분 수정

- app/recipes/views.py
> Fix: 스텝 이미지 빈 칸, 검색기능에서 step 내용은 제외

- app/users/views.py
> Fix: 알림받기 상태 항상 1로 보내던거 수정

- app/recipes/utils.py
- app/recipes/views.py
- app/users/customs/authentication.py
- app/users/customs/exception_handler.py
- app/users/views.py
- 도메인에 쿠키 추가
- 댓글 순서대로 정렬
- 이미지 없으면 `null`로 반환하도록 수정
> Fix: 수정사항 반영 

- app/users/customs/authentication.py
- app/users/views.py
> HOTFIX: 쿠키 도메인 host 설정 변경

- app/users/customs/authentication.py
- app/users/views.py
> HOTFIX: 도메인 host 가져오는 부분 수정2

- app/users/customs/authentication.py
- app/users/customs/exception_handler.py
- app/users/views.py
> HOTFIX: 쿠키 도메인 설정 수정

- app/common/utils/image_utils.py
- app/recipes/utils.py
- app/recipes/views.py
- app/users/views.py
> Fix: 이미지 처리 함수 수정

- app/users/serializers.py
> Fix: 유저 닉네임 업데이트 수정

- app/common/utils/image_utils.py
- app/users/serializers.py
> Fix: 유저 닉네임 수정 API, 카테고리 이미지 수정

- app/common/utils/image_utils.py
- app/users/customs/authentication.py
- app/users/utils.py
> HOTFIX: 유저 닉네임 변경 수정 및 이미지 URL 겹치는 것 수정

- app/recipes/views.py
> HOTFIX: 레시피 조회는 로그인 없이도 가능하게 수정

- app/collabo/utils/interaction_utils.py
- app/collabo/utils/similary_utils.py
- app/recipes/views.py
> Feat: 특정 레시피 클릭 안했을 시 댓글, 좋아요, 북마크 합으로 레시피 추천

- app/config/settings.py
- app/users/services.py
- app/users/utils.py
- app/users/views.py
> Feat: 개발환경에 쿠키 설정 가능

- app/users/utils.py
> Fix: 쿠키 도메인 설정 변경

- app/main/views.py
> Fix: 금주의 레시피 지난주 좋아요, 북마크 수로만 계산
